version: '3.7'
services:
  graphql-server:
    build:
      context: ../
      dockerfile: build/package/Dockerfile
      target: release
    ports:
      - 4000:4000
    networks:
      - hackernews-go

networks:
  hackernews-go:
    external: true
