// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Link struct {
	ID          string `json:"id"`
	Description string `json:"description"`
	URL         string `json:"url"`
}
