// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"github.com/ncalibey/hackernews-go/internal/prisma"
)

type AuthPayload struct {
	Token *string      `json:"token"`
	User  *prisma.User `json:"user"`
}
